services:
  prode-mysql-db:
    image: mysql:latest
    container_name: prode_mysql_container
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - prode_mysql_persistence:/var/lib/mysql

volumes:
  prode_mysql_persistence:
    name: "prode_mysql_persistence"
