services:
  fixture-mysql-db:
    image: mysql:latest
    container_name: fixture_mysql_container
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - fixture_mysql_persistence:/var/lib/mysql

volumes:
  fixture_mysql_persistence:
    name: "fixture_mysql_persistence"
